### ISSUE TITLE
[Question] hz update failed in easy_note

### ISSUE THREAD

**Issue by liuxiaocs7** [cloudwego/biz-demo#25]
**Describe the bug**

when run these code under `easy_note`, `hz update` failed (hz version v0.5.1)

https://github.com/cloudwego/biz-demo/blob/0c8638d5de2b901d7f7574342acec261b85f7ad8/easy_note/cmd/api/Makefile#L1-L5

Accoding the [doc](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#new), there no `mod/module` param in `hz update`

**To Reproduce**

1. `go install github.com/cloudwego/hertz/cmd/hz@latest`
2. `cd biz-demo/easy_note/cmd/api`
3. `make update_api`

```
hz update -mod github.com/cloudwego/biz-demo/easy_note -idl ../../idl/api.thrift
Incorrect Usage: flag provided but not defined: -mod

NAME:
   hz update - Update an existing Hertz project

USAGE:
   hz update command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --idl value [ --idl value ]                                            Specify the IDL file path. (.thrift or .proto)
   --out_dir value                                                        Specify the project path.
   --handler_dir value                                                    Specify the handler path.
   --model_dir value                                                      Specify the model path.
   --client_dir value                                                     Specify the client path. If not specified, IDL generated path is used for 'client' command; no client code is generated for 'new' co
mmand
   --proto_path value, -I value [ --proto_path value, -I value ]          Add an IDL search path for includes. (Valid only if idl is protobuf)
   --thriftgo value, -t value [ --thriftgo value, -t value ]              Specify arguments for the thriftgo. ({flag}={value})
   --protoc value, -p value [ --protoc value, -p value ]                  Specify arguments for the protoc. ({flag}={value})
   --option_package value, -P value [ --option_package value, -P value ]  Specify the package path. ({include_path}={import_path})
   --no_recurse                                                           Generate master model only. (default: false)
   --json_enumstr                                                         Use string instead of num for json enums when idl is thrift. (default: false)
   --unset_omitempty                                                      Remove 'omitempty' tag for generated struct. (default: false)
   --pb_camel_json_tag                                                    Convert Name style for json tag to camel(Only works protobuf). (default: false)
   --snake_tag                                                            Use snake_case style naming for tags. (Only works for 'form', 'query', 'json') (default: false)
   --exclude_file value, -E value [ --exclude_file value, -E value ]      Specify the files that do not need to be updated.
   --customize_package value                                              Specify the package template. ({{Template Profile}}:)
   --handler_by_method                                                    Generate a separate handler file for each method. (default: false)
   --protoc-plugins value [ --protoc-plugins value ]                      Specify plugins for the protoc. ({plugin_name}:{options}:{out_dir})
   --thrift-plugins value [ --thrift-plugins value ]                      Specify plugins for the thriftgo. ({plugin_name}:{options})
   --help, -h                                                             show help (default: false)
[ERROR]/home/liuxiao/workspace/golang/pkg/mod/github.com/cloudwego/hertz/cmd/hz@v0.5.1/main.go:42: flag provided but not defined: -mod
```

**Expected behavior**

This parameter may exist in previous hertz versions, now how to handle the go module problem in the current version of hertz?

For example, code structure like this, if my project is not under `GOPATH`, how can i use `hz update` to change api interface when interface changed.

I'm newbie from hertz, looking forward to your reply, thx.

```
easy_note
    cmd
        api   -->  hertz
        note  -->  kitex
        user  -->  kitex
    idl
    kitex_gen
    ...
go.mod
```

**Screenshots**

No.

**Kitex version:**

No.

**Environment:**

```
[liuxiao@dev easy_note]$ go env
GO111MODULE="on"                       
GOARCH="amd64"                         
GOBIN=""                               
GOCACHE="/home/liuxiao/.cache/go-build"
GOENV="/home/liuxiao/.config/go/env"   
GOEXE=""                               
GOEXPERIMENT=""                        
GOFLAGS=""                             
GOHOSTARCH="amd64"                     
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/liuxiao/workspace/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/liuxiao/workspace/golang"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/liuxiao/go/go1.18.10"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/liuxiao/go/go1.18.10/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/liuxiao/Code/GoProjects/biz-demo/easy_note/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2861411109=/tmp/go-build -gno-record-gcc-switches"
```

**Additional context**

No.

**Comment by li-jin-gou** [comment]
this is mistake and not special mod when use update



---Original---
From: "Liu ***@***.***&gt;
Date: Wed, Feb 1, 2023 01:34 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cloudwego/biz-demo] [Question] hz update failed in easy_note (Issue#25)




 
Describe the bug
 
when run these code under easy_note, hz update failed (hz version v0.5.1)
 
https://github.com/cloudwego/biz-demo/blob/0c8638d5de2b901d7f7574342acec261b85f7ad8/easy_note/cmd/api/Makefile#L1-L5
 
Accoding the doc, there no mod/module param in hz update
 
To Reproduce
 
Steps to reproduce the behavior:
  
go install ***@***.***
 
cd biz-demo/easy_note/cmd/api
 
make update_api
 
See error
  hz update -mod github.com/cloudwego/biz-demo/easy_note -idl ../../idl/api.thrift Incorrect Usage: flag provided but not defined: -mod NAME:    hz update - Update an existing Hertz project USAGE:    hz update command [command options] [arguments...] COMMANDS:    help, h  Shows a list of commands or help for one command    help, h  Shows a list of commands or help for one command OPTIONS:    --idl value [ --idl value ]                                            Specify the IDL file path. (.thrift or .proto)    --out_dir value                                                        Specify the project path.    --handler_dir value                                                    Specify the handler path.    --model_dir value                                                      Specify the model path.    --client_dir value                                                     Specify the client path. If not specified, IDL generated path is used for 'client' command; no client code is generated for 'new' co mmand    --proto_path value, -I value [ --proto_path value, -I value ]          Add an IDL search path for includes. (Valid only if idl is protobuf)    --thriftgo value, -t value [ --thriftgo value, -t value ]              Specify arguments for the thriftgo. ({flag}={value})    --protoc value, -p value [ --protoc value, -p value ]                  Specify arguments for the protoc. ({flag}={value})    --option_package value, -P value [ --option_package value, -P value ]  Specify the package path. ({include_path}={import_path})    --no_recurse                                                           Generate master model only. (default: false)    --json_enumstr                                                         Use string instead of num for json enums when idl is thrift. (default: false)    --unset_omitempty                                                      Remove 'omitempty' tag for generated struct. (default: false)    --pb_camel_json_tag                                                    Convert Name style for json tag to camel(Only works protobuf). (default: false)    --snake_tag                                                            Use snake_case style naming for tags. (Only works for 'form', 'query', 'json') (default: false)    --exclude_file value, -E value [ --exclude_file value, -E value ]      Specify the files that do not need to be updated.    --customize_package value                                              Specify the package template. ({{Template Profile}}:)    --handler_by_method                                                    Generate a separate handler file for each method. (default: false)    --protoc-plugins value [ --protoc-plugins value ]                      Specify plugins for the protoc. ({plugin_name}:{options}:{out_dir})    --thrift-plugins value [ --thrift-plugins value ]                      Specify plugins for the thriftgo. ({plugin_name}:{options})    --help, -h                                                             show help (default: false) ***@***.***/main.go:42: flag provided but not defined: -mod  
Expected behavior
 
This parameter may exist in previous hertz versions, now how to handle the go module problem in the current version of hertz?
 
For example, code structure like this, if my project is not under GOPATH, how can i use hz update to change api interface when interface changed.
 
I'm newbie from hertz, looking forward to your reply, thx.
 easy_note     cmd         api   --&gt;  hertz         note  --&gt;  kitex         user  --&gt;  kitex     idl     kitex_gen     ... go.mod  
Screenshots
 
No.
 
Kitex version:
 
No.
 
Environment:
 ***@***.*** easy_note]$ go env GO111MODULE="on"                        GOARCH="amd64"                          GOBIN=""                                GOCACHE="/home/liuxiao/.cache/go-build" GOENV="/home/liuxiao/.config/go/env"    GOEXE=""                                GOEXPERIMENT=""                         GOFLAGS=""                              GOHOSTARCH="amd64"                      GOHOSTOS="linux" GOINSECURE="" GOMODCACHE="/home/liuxiao/workspace/golang/pkg/mod" GONOPROXY="" GONOSUMDB="" GOOS="linux" GOPATH="/home/liuxiao/workspace/golang" GOPRIVATE="" GOPROXY="https://goproxy.cn,direct" GOROOT="/home/liuxiao/go/go1.18.10" GOSUMDB="off" GOTMPDIR="" GOTOOLDIR="/home/liuxiao/go/go1.18.10/pkg/tool/linux_amd64" GOVCS="" GOVERSION="go1.18.10" GCCGO="gccgo" GOAMD64="v1" AR="ar" CC="gcc" CXX="g++" CGO_ENABLED="1" GOMOD="/home/liuxiao/Code/GoProjects/biz-demo/easy_note/go.mod" GOWORK="" CGO_CFLAGS="-g -O2" CGO_CPPFLAGS="" CGO_CXXFLAGS="-g -O2" CGO_FFLAGS="-g -O2" CGO_LDFLAGS="-g -O2" PKG_CONFIG="pkg-config" GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2861411109=/tmp/go-build -gno-record-gcc-switches"  
Additional context
 
No.

**Comment by liuxiaocs7** [comment]
Sorry, I don't quite understand your reply. Can you explain it in more detail, thx.

Add some attempts:

when use (remove `-mod` in hz 0.5.1)
```
update_api:
	hz update -idl ../../idl/api.thrift
```

and result:

```
[liuxiao@dev api]$ make update_api
hz update -idl ../../idl/api.thrift
plugin thriftgo_gen_hertz returns error: exit status 2, cause:
[WARN] stdout:

[WARN] stderr:
[ERROR]/home/liuxiao/workspace/golang/pkg/mod/github.com/cloudwego/hertz/cmd/hz@v0.5.1/thrift/plugin.go:103: get go package failed: project package name is not set

execute plugin 'hertz' failed: exit status 4

make: *** [Makefile:5: update_api] Error 4
```

So how to specify mod under this project structure?

**Comment by FGYFFFF** [comment]
when you use 'update' command, hz will search 'module' from "go.mod", but in this peoject, the "go.mod" file have been moved to other folder. I will fix the problem.

**Comment by liuxiaocs7** [comment]
> when you use 'update' command, hz will search 'module' from "go.mod", but in this peoject, the "go.mod" file have been moved to other folder. I will fix the problem.

Thank you for your reply, look forward to the update.

**Comment by FGYFFFF** [comment]
https://github.com/cloudwego/biz-demo/pull/26 ，可以看下这个pr，把功能都优化了下
